// Short, plain-English reference data for Excel functions, shown in the
// function-help popover on the tree. One sentence per summary (office-worker
// friendly, no jargon); `returns` is a short phrase. `syntax` is derived from
// FUNCTION_ARG_NAMES in the functionDocs index, so it is not duplicated here.
//
// FULL-COVERAGE INVARIANT: every key in FUNCTION_ARG_NAMES must have a
// summary + returns here (enforced by functionDocs.test.ts). A few everyday
// functions (LET, SUMIFS, IFS, CHOOSE, …) are not in FUNCTION_ARG_NAMES but
// are still documented here via FUNCTION_SYNTAX_ARGS so their syntax renders
// correctly.

export const FUNCTION_SUMMARIES: Record<string, string> = {
  // ── Logical ────────────────────────────────────────────────
  IF: 'Checks a condition; returns one value if true, another if false.',
  IFERROR: 'Returns the value, or a fallback if it results in an error.',
  IFNA: 'Returns the value, or a fallback if it results in #N/A.',
  NOT: 'Reverses a logical value: TRUE becomes FALSE and vice versa.',
  TRUE: 'Returns the logical value TRUE.',
  FALSE: 'Returns the logical value FALSE.',
  SWITCH: 'Matches a value against pairs and returns the first match result.',

  // ── Math & trig ────────────────────────────────────────────
  SUM: 'Adds up all the numbers.',
  AVERAGE: 'Finds the average of the numbers.',
  AVERAGEA: 'Finds the average, counting text and FALSE as zero.',
  COUNT: 'Counts how many cells contain numbers.',
  COUNTA: 'Counts how many cells are not empty.',
  COUNTIF: 'Counts cells that meet one condition.',
  MAX: 'Finds the largest number.',
  MIN: 'Finds the smallest number.',
  PRODUCT: 'Multiplies all the numbers together.',
  ROUND: 'Rounds a number to a set number of digits.',
  ROUNDUP: 'Rounds a number up, away from zero.',
  ROUNDDOWN: 'Rounds a number down, toward zero.',
  MROUND: 'Rounds a number to the nearest multiple.',
  ABS: 'Gives the number without its sign (always positive).',
  SQRT: 'Finds the square root of a number.',
  POWER: 'Raises a number to a given power.',
  MOD: 'Gives the remainder after dividing two numbers.',
  INT: 'Rounds a number down to the nearest whole number.',
  FLOOR: 'Rounds a number down to the nearest multiple.',
  'FLOOR.MATH': 'Rounds a number down to the nearest multiple.',
  CEILING: 'Rounds a number up to the nearest multiple.',
  'CEILING.MATH': 'Rounds a number up to the nearest multiple.',
  SUMPRODUCT: 'Multiplies matching values across ranges and adds the results.',
  RAND: 'Returns a random number between 0 and 1.',
  RANDBETWEEN: 'Returns a random whole number between two values.',
  PI: 'Returns the number pi (3.14159…).',
  EXP: 'Raises e to a given power.',
  LN: 'Finds the natural logarithm of a number.',
  LOG: 'Finds the logarithm of a number to a given base.',
  LOG10: 'Finds the base-10 logarithm of a number.',
  SIN: 'Finds the sine of an angle.',
  COS: 'Finds the cosine of an angle.',
  TAN: 'Finds the tangent of an angle.',
  ASIN: 'Finds the angle from a sine value.',
  ACOS: 'Finds the angle from a cosine value.',
  ATAN: 'Finds the angle from a tangent value.',
  ATAN2: 'Finds the angle from x and y coordinates.',
  SIGN: 'Tells whether a number is negative, zero, or positive.',
  TRUNC: 'Truncates a number, removing decimals without rounding.',

  // ── Lookup & reference ─────────────────────────────────────
  VLOOKUP: 'Looks up a value in the first column and returns a value from the same row.',
  HLOOKUP: 'Looks up a value in the first row and returns a value from the same column.',
  XLOOKUP: 'Looks up a value in a range and returns a matching value from another range.',
  INDEX: 'Returns a value at a given position in a range.',
  MATCH: 'Finds the position of a value within a range.',
  OFFSET: 'Returns a range shifted by rows and columns from a starting point.',
  INDIRECT: 'Turns text that looks like a reference into an actual reference.',
  ROW: 'Returns the row number of a reference.',
  COLUMN: 'Returns the column number of a reference.',
  ROWS: 'Counts how many rows are in a range.',
  COLUMNS: 'Counts how many columns are in a range.',
  AREAS: 'Counts how many areas a reference is made of.',

  // ── Text ───────────────────────────────────────────────────
  CONCATENATE: 'Joins several pieces of text into one.',
  CONCAT: 'Joins several pieces of text into one.',
  TEXTJOIN: 'Joins text with a separator, skipping empty cells.',
  LEFT: 'Takes characters from the left side of text.',
  RIGHT: 'Takes characters from the right side of text.',
  MID: 'Takes characters from the middle of text.',
  LEN: 'Counts the characters in a piece of text.',
  UPPER: 'Converts text to capital letters.',
  LOWER: 'Converts text to lowercase letters.',
  PROPER: 'Capitalizes the first letter of each word.',
  TRIM: 'Removes extra spaces from text.',
  SUBSTITUTE: 'Replaces specific text with new text.',
  REPLACE: 'Replaces characters at a set position.',
  TEXT: 'Formats a number as text using a format pattern.',
  VALUE: 'Turns text that looks like a number into a number.',
  FIND: 'Finds text within other text (case-sensitive).',
  SEARCH: 'Finds text within other text (not case-sensitive).',
  REPT: 'Repeats text a set number of times.',
  CLEAN: 'Removes non-printable characters from text.',
  EXACT: 'Checks whether two pieces of text are identical.',

  // ── Date & time ────────────────────────────────────────────
  TODAY: 'Returns the current date.',
  NOW: 'Returns the current date and time.',
  YEAR: 'Extracts the year from a date.',
  MONTH: 'Extracts the month from a date.',
  DAY: 'Extracts the day of the month from a date.',
  HOUR: 'Extracts the hour from a time.',
  MINUTE: 'Extracts the minute from a time.',
  SECOND: 'Extracts the second from a time.',
  DATE: 'Builds a date from year, month, and day.',
  TIME: 'Builds a time from hour, minute, and second.',
  DATEDIF: 'Counts the days, months, or years between two dates.',
  WEEKDAY: 'Returns the day of the week for a date.',
  WEEKNUM: 'Returns the week number of a date in the year.',
  EOMONTH: 'Returns the last day of the month, months away.',
  EDATE: 'Returns a date a set number of months away.',
  WORKDAY: 'Returns a date a set number of working days away.',
  NETWORKDAYS: 'Counts working days between two dates.',
  YEARFRAC: 'Returns the fraction of a year between two dates.',

  // ── Statistical ────────────────────────────────────────────
  STDEV: 'Measures how spread out the numbers are.',
  'STDEV.S': 'Measures how spread out the numbers are (sample).',
  STDEVP: 'Measures how spread out the numbers are (population).',
  'STDEV.P': 'Measures how spread out the numbers are (population).',
  VAR: 'Measures how spread out the numbers are (sample).',
  'VAR.S': 'Measures how spread out the numbers are (sample).',
  VARP: 'Measures how spread out the numbers are (population).',
  'VAR.P': 'Measures how spread out the numbers are (population).',
  MEDIAN: 'Finds the middle number in a list.',
  MODE: 'Finds the most common number in a list.',
  'MODE.SNGL': 'Finds the most common number in a list.',
  'MODE.MULT': 'Finds all the most common numbers in a list.',
  RANK: 'Gives the rank of a number within a list.',
  'RANK.EQ': 'Gives the rank of a number within a list.',
  'RANK.AVG': 'Gives the rank of a number, averaging tied ranks.',
  LARGE: 'Returns the k-th largest value in a range.',
  SMALL: 'Returns the k-th smallest value in a range.',
  PERCENTILE: 'Returns the value at a given percentile.',
  'PERCENTILE.EXC': 'Returns the value at a given percentile.',
  'PERCENTILE.INC': 'Returns the value at a given percentile.',
  QUARTILE: 'Returns the value at a given quartile.',
  'QUARTILE.EXC': 'Returns the value at a given quartile.',
  'QUARTILE.INC': 'Returns the value at a given quartile.',
  CORREL: 'Measures how two sets of numbers move together.',
  'COVARIANCE.P': 'Measures how two sets of numbers vary together.',
  'COVARIANCE.S': 'Measures how two sets of numbers vary together.',
  COVAR: 'Measures how two sets of numbers vary together.',
  FORECAST: 'Predicts a future value from known points.',
  'FORECAST.LINEAR': 'Predicts a future value from known points.',
  TREND: 'Fits a straight line and predicts values.',
  GROWTH: 'Fits an exponential curve and predicts values.',
  'NORM.DIST': 'Returns the normal distribution for a value.',
  NORMDIST: 'Returns the normal distribution for a value.',
  'NORM.INV': 'Returns the value at a probability in a normal distribution.',
  NORMINV: 'Returns the value at a probability in a normal distribution.',

  // ── Information ────────────────────────────────────────────
  ISERROR: 'Checks whether a value is any error.',
  ISNUMBER: 'Checks whether a value is a number.',
  ISTEXT: 'Checks whether a value is text.',
  ISBLANK: 'Checks whether a cell is empty.',
  ISLOGICAL: 'Checks whether a value is TRUE or FALSE.',
  ISNA: 'Checks whether a value is the #N/A error.',
  ISERR: 'Checks whether a value is an error, except #N/A.',
  ISEVEN: 'Checks whether a number is even.',
  ISODD: 'Checks whether a number is odd.',
  ISNONTEXT: 'Checks whether a value is not text.',
  ISREF: 'Checks whether a value is a cell reference.',
  TYPE: 'Tells the data type of a value.',
  N: 'Converts a value to a number.',
  NA: 'Returns the #N/A error.',
  'ERROR.TYPE': 'Returns a number that identifies an error type.',
  INFO: 'Returns environment information, such as the current folder.',
  CELL: 'Returns information about a cell, such as its address.',

  // ── Financial ──────────────────────────────────────────────
  PMT: 'Calculates the payment for a loan.',
  FV: 'Calculates the future value of an investment.',
  PV: 'Calculates the present value of an investment.',
  RATE: 'Calculates the interest rate of a loan or investment.',
  NPER: 'Calculates how many payments a loan needs.',
  NPV: 'Calculates the net present value of cash flows.',
  IRR: 'Calculates the internal rate of return.',
  SLN: 'Calculates straight-line depreciation.',
  SYD: 'Calculates sum-of-years-digits depreciation.',
  DB: 'Calculates fixed-declining-balance depreciation.',
  DDB: 'Calculates double-declining-balance depreciation.',
  VDB: 'Calculates declining-balance depreciation.',

  // ── Engineering ────────────────────────────────────────────
  DEC2BIN: 'Converts a decimal number to binary.',
  DEC2HEX: 'Converts a decimal number to hexadecimal.',
  DEC2OCT: 'Converts a decimal number to octal.',
  BIN2DEC: 'Converts a binary number to decimal.',
  BIN2HEX: 'Converts a binary number to hexadecimal.',
  BIN2OCT: 'Converts a binary number to octal.',
  HEX2DEC: 'Converts a hexadecimal number to decimal.',
  HEX2BIN: 'Converts a hexadecimal number to binary.',
  HEX2OCT: 'Converts a hexadecimal number to octal.',
  OCT2DEC: 'Converts an octal number to decimal.',
  OCT2BIN: 'Converts an octal number to binary.',
  OCT2HEX: 'Converts an octal number to hexadecimal.',
  BITAND: 'Performs a bitwise AND operation.',
  BITOR: 'Performs a bitwise OR operation.',
  BITXOR: 'Performs a bitwise XOR operation.',
  BITLSHIFT: 'Shifts bits to the left.',
  BITRSHIFT: 'Shifts bits to the right.',

  // ── Database ───────────────────────────────────────────────
  DSUM: 'Adds values in a database that match criteria.',
  DAVERAGE: 'Averages values in a database that match criteria.',
  DCOUNT: 'Counts numeric cells in a database that match criteria.',
  DMAX: 'Finds the largest value in a database that matches criteria.',
  DMIN: 'Finds the smallest value in a database that matches criteria.',
  DGET: 'Returns a single value from a database that matches criteria.',
  DPRODUCT: 'Multiplies values in a database that match criteria.',
  DSTDEV: 'Estimates standard deviation from a database sample.',
  DSTDEVP: 'Estimates standard deviation from a database population.',
  DVAR: 'Estimates variance from a database sample.',
  DVARP: 'Estimates variance from a database population.',

  // ── Array / dynamic ────────────────────────────────────────
  TRANSPOSE: 'Flips rows and columns.',
  UNIQUE: 'Returns only the unique values from a range.',
  SORT: 'Sorts a range.',
  SORTBY: 'Sorts a range according to another range.',
  FILTER: 'Returns only the values that meet a condition.',
  SEQUENCE: 'Creates a list of numbers in rows and columns.',
  RANDARRAY: 'Creates a range of random numbers.',

  // ── Everyday functions not in FUNCTION_ARG_NAMES ───────────
  LET: 'Names values so a formula stays short and easy to read.',
  IFS: 'Checks conditions in order and returns the first match.',
  SUMIFS: 'Adds values that meet multiple conditions.',
  COUNTIFS: 'Counts cells that meet multiple conditions.',
  AVERAGEIFS: 'Averages cells that meet multiple conditions.',
  MINIFS: 'Finds the smallest value that meets multiple conditions.',
  MAXIFS: 'Finds the largest value that meets multiple conditions.',
  CHOOSE: 'Picks a value from a list by its position number.',
};

export const FUNCTION_RETURNS: Record<string, string> = {
  // ── Logical ────────────────────────────────────────────────
  IF: 'The value from the true or false branch',
  IFERROR: 'The value, or your fallback',
  IFNA: 'The value, or your fallback',
  NOT: 'The opposite logical value',
  TRUE: 'TRUE',
  FALSE: 'FALSE',
  SWITCH: 'The first matching result',

  // ── Math & trig ────────────────────────────────────────────
  SUM: 'The total of all numbers',
  AVERAGE: 'The average',
  AVERAGEA: 'The average',
  COUNT: 'The number of numeric cells',
  COUNTA: 'The number of non-empty cells',
  COUNTIF: 'The count',
  MAX: 'The largest value',
  MIN: 'The smallest value',
  PRODUCT: 'The product',
  ROUND: 'The rounded number',
  ROUNDUP: 'The rounded-up number',
  ROUNDDOWN: 'The rounded-down number',
  MROUND: 'The rounded number',
  ABS: 'A positive number',
  SQRT: 'The square root',
  POWER: 'The result',
  MOD: 'The remainder',
  INT: 'A whole number',
  FLOOR: 'The rounded-down number',
  'FLOOR.MATH': 'The rounded-down number',
  CEILING: 'The rounded-up number',
  'CEILING.MATH': 'The rounded-up number',
  SUMPRODUCT: 'The weighted total',
  RAND: 'A random number',
  RANDBETWEEN: 'A random number',
  PI: 'Pi',
  EXP: 'The result',
  LN: 'The logarithm',
  LOG: 'The logarithm',
  LOG10: 'The logarithm',
  SIN: 'The sine',
  COS: 'The cosine',
  TAN: 'The tangent',
  ASIN: 'The angle',
  ACOS: 'The angle',
  ATAN: 'The angle',
  ATAN2: 'The angle',
  SIGN: '−1, 0, or 1',
  TRUNC: 'The truncated number',

  // ── Lookup & reference ─────────────────────────────────────
  VLOOKUP: 'The matching value from the row',
  HLOOKUP: 'The matching value from the column',
  XLOOKUP: 'The matching value',
  INDEX: 'The value at that position',
  MATCH: 'The position number',
  OFFSET: 'A range',
  INDIRECT: 'The referenced value',
  ROW: 'A row number',
  COLUMN: 'A column number',
  ROWS: 'The row count',
  COLUMNS: 'The column count',
  AREAS: 'The area count',

  // ── Text ───────────────────────────────────────────────────
  CONCATENATE: 'The joined text',
  CONCAT: 'The joined text',
  TEXTJOIN: 'The joined text',
  LEFT: 'The extracted text',
  RIGHT: 'The extracted text',
  MID: 'The extracted text',
  LEN: 'The character count',
  UPPER: 'Uppercase text',
  LOWER: 'Lowercase text',
  PROPER: 'Proper-cased text',
  TRIM: 'Cleaned text',
  SUBSTITUTE: 'The updated text',
  REPLACE: 'The updated text',
  TEXT: 'Formatted text',
  VALUE: 'The number',
  FIND: 'The position of the text',
  SEARCH: 'The position of the text',
  REPT: 'Repeated text',
  CLEAN: 'Cleaned text',
  EXACT: 'TRUE or FALSE',

  // ── Date & time ────────────────────────────────────────────
  TODAY: 'Today’s date',
  NOW: 'The current date and time',
  YEAR: 'The year',
  MONTH: 'The month number',
  DAY: 'The day number',
  HOUR: 'The hour',
  MINUTE: 'The minute',
  SECOND: 'The second',
  DATE: 'A date',
  TIME: 'A time',
  DATEDIF: 'The difference',
  WEEKDAY: 'A day number',
  WEEKNUM: 'The week number',
  EOMONTH: 'A date',
  EDATE: 'A date',
  WORKDAY: 'A date',
  NETWORKDAYS: 'The working-day count',
  YEARFRAC: 'A fraction of a year',

  // ── Statistical ────────────────────────────────────────────
  STDEV: 'The spread',
  'STDEV.S': 'The spread',
  STDEVP: 'The spread',
  'STDEV.P': 'The spread',
  VAR: 'The spread',
  'VAR.S': 'The spread',
  VARP: 'The spread',
  'VAR.P': 'The spread',
  MEDIAN: 'The middle value',
  MODE: 'The most common value',
  'MODE.SNGL': 'The most common value',
  'MODE.MULT': 'The most common values',
  RANK: 'The rank',
  'RANK.EQ': 'The rank',
  'RANK.AVG': 'The rank',
  LARGE: 'The k-th largest value',
  SMALL: 'The k-th smallest value',
  PERCENTILE: 'The value at the percentile',
  'PERCENTILE.EXC': 'The value at the percentile',
  'PERCENTILE.INC': 'The value at the percentile',
  QUARTILE: 'The value at the quartile',
  'QUARTILE.EXC': 'The value at the quartile',
  'QUARTILE.INC': 'The value at the quartile',
  CORREL: 'A number from −1 to 1',
  'COVARIANCE.P': 'A number',
  'COVARIANCE.S': 'A number',
  COVAR: 'A number',
  FORECAST: 'The predicted value',
  'FORECAST.LINEAR': 'The predicted value',
  TREND: 'The predicted values',
  GROWTH: 'The predicted values',
  'NORM.DIST': 'Probability or density',
  NORMDIST: 'Probability or density',
  'NORM.INV': 'The value',
  NORMINV: 'The value',

  // ── Information ────────────────────────────────────────────
  ISERROR: 'TRUE or FALSE',
  ISNUMBER: 'TRUE or FALSE',
  ISTEXT: 'TRUE or FALSE',
  ISBLANK: 'TRUE or FALSE',
  ISLOGICAL: 'TRUE or FALSE',
  ISNA: 'TRUE or FALSE',
  ISERR: 'TRUE or FALSE',
  ISEVEN: 'TRUE or FALSE',
  ISODD: 'TRUE or FALSE',
  ISNONTEXT: 'TRUE or FALSE',
  ISREF: 'TRUE or FALSE',
  TYPE: 'A type number',
  N: 'A number',
  NA: 'The #N/A error',
  'ERROR.TYPE': 'An error number',
  INFO: 'The requested info',
  CELL: 'The cell info',

  // ── Financial ──────────────────────────────────────────────
  PMT: 'The payment amount',
  FV: 'The future value',
  PV: 'The present value',
  RATE: 'The rate',
  NPER: 'The number of periods',
  NPV: 'The net present value',
  IRR: 'The rate of return',
  SLN: 'The depreciation per period',
  SYD: 'The depreciation',
  DB: 'The depreciation',
  DDB: 'The depreciation',
  VDB: 'The depreciation',

  // ── Engineering ────────────────────────────────────────────
  DEC2BIN: 'Binary text',
  DEC2HEX: 'Hexadecimal text',
  DEC2OCT: 'Octal text',
  BIN2DEC: 'A decimal number',
  BIN2HEX: 'Hexadecimal text',
  BIN2OCT: 'Octal text',
  HEX2DEC: 'A decimal number',
  HEX2BIN: 'Binary text',
  HEX2OCT: 'Octal text',
  OCT2DEC: 'A decimal number',
  OCT2BIN: 'Binary text',
  OCT2HEX: 'Hexadecimal text',
  BITAND: 'The result',
  BITOR: 'The result',
  BITXOR: 'The result',
  BITLSHIFT: 'The result',
  BITRSHIFT: 'The result',

  // ── Database ───────────────────────────────────────────────
  DSUM: 'The total',
  DAVERAGE: 'The average',
  DCOUNT: 'The count',
  DMAX: 'The largest value',
  DMIN: 'The smallest value',
  DGET: 'The value',
  DPRODUCT: 'The product',
  DSTDEV: 'The standard deviation',
  DSTDEVP: 'The standard deviation',
  DVAR: 'The variance',
  DVARP: 'The variance',

  // ── Array / dynamic ────────────────────────────────────────
  TRANSPOSE: 'The flipped range',
  UNIQUE: 'The unique values',
  SORT: 'The sorted range',
  SORTBY: 'The sorted range',
  FILTER: 'The matching values',
  SEQUENCE: 'A list of numbers',
  RANDARRAY: 'Random numbers',

  // ── Everyday functions not in FUNCTION_ARG_NAMES ───────────
  LET: 'The final calculation result',
  IFS: 'The first matching result',
  SUMIFS: 'The total',
  COUNTIFS: 'The count',
  AVERAGEIFS: 'The average',
  MINIFS: 'The smallest value',
  MAXIFS: 'The largest value',
  CHOOSE: 'The chosen value',
};

// Argument lists for everyday functions that are NOT in FUNCTION_ARG_NAMES
// (so their syntax still renders correctly). SUMIFS/COUNTIFS/… are handled by
// getArgName via special cases, but never appear in the args map.
export const FUNCTION_SYNTAX_ARGS: Record<string, string[]> = {
  LET: ['name1', 'value1', 'name2', 'value2', 'calculation'],
  IFS: ['logical_test1', 'value_if_true1', 'logical_test2', 'value_if_true2'],
  SUMIFS: ['sum_range', 'criteria_range1', 'criteria1'],
  COUNTIFS: ['criteria_range1', 'criteria1'],
  AVERAGEIFS: ['average_range', 'criteria_range1', 'criteria1'],
  MINIFS: ['min_range', 'criteria_range1', 'criteria1'],
  MAXIFS: ['max_range', 'criteria_range1', 'criteria1'],
  CHOOSE: ['index_num', 'value1', 'value2'],
};

// 0-based indices of optional arguments, so the syntax readout can wrap them
// in square brackets like Microsoft's own docs: =IF(test, [value_if_false]).
// Functions absent from this map are treated as all-required.
export const FUNCTION_OPTIONAL_ARGS: Record<string, number[]> = {
  // Logical
  SWITCH: [3],
  // Math
  LOG: [1],
  TRUNC: [1],
  'FLOOR.MATH': [1, 2],
  'CEILING.MATH': [1, 2],
  // Lookup & reference
  HLOOKUP: [3],
  XLOOKUP: [3, 4, 5],
  INDEX: [1, 2, 3],
  MATCH: [2],
  OFFSET: [3, 4],
  INDIRECT: [1],
  ROW: [0],
  COLUMN: [0],
  // Text
  LEFT: [1],
  RIGHT: [1],
  SUBSTITUTE: [3],
  TEXT: [1],
  FIND: [2],
  SEARCH: [2],
  // Date & time
  WEEKDAY: [1],
  WEEKNUM: [1],
  WORKDAY: [2],
  NETWORKDAYS: [2],
  YEARFRAC: [2],
  // Statistical
  RANK: [2],
  'RANK.EQ': [2],
  'RANK.AVG': [2],
  // Information
  CELL: [1],
  // Financial
  PMT: [2, 3, 4],
  FV: [2, 3, 4],
  PV: [2, 3, 4],
  RATE: [2, 3, 4, 5],
  NPER: [2, 3, 4],
  IRR: [1],
  DB: [4],
  DDB: [5],
  VDB: [5, 6],
  // Engineering (base conversions: "places" optional)
  DEC2BIN: [1],
  DEC2HEX: [1],
  DEC2OCT: [1],
  BIN2HEX: [1],
  BIN2OCT: [1],
  HEX2BIN: [1],
  HEX2OCT: [1],
  OCT2BIN: [1],
  OCT2HEX: [1],
  // Database (criteria optional)
  DSUM: [2],
  DAVERAGE: [2],
  DCOUNT: [2],
  DMAX: [2],
  DMIN: [2],
  DGET: [2],
  DPRODUCT: [2],
  DSTDEV: [2],
  DSTDEVP: [2],
  DVAR: [2],
  DVARP: [2],
  // Dynamic arrays
  UNIQUE: [1, 2],
  SORT: [1, 2, 3],
  SORTBY: [2],
  FILTER: [2],
  SEQUENCE: [1, 2, 3],
  RANDARRAY: [1, 2, 3, 4],
  // IFS pairs (second pair onward optional)
  IFS: [2, 3],
  // Variadic list functions: the first argument is required, the rest
  // optional, e.g. SUM(number1, [number2], [number3], …).
  SUM: [1, 2],
  AVERAGE: [1, 2],
  AVERAGEA: [1, 2],
  COUNT: [1, 2],
  COUNTA: [1, 2],
  PRODUCT: [1, 2],
  SUMPRODUCT: [1, 2],
  STDEV: [1, 2],
  'STDEV.S': [1, 2],
  STDEVP: [1, 2],
  'STDEV.P': [1, 2],
  VAR: [1, 2],
  'VAR.S': [1, 2],
  VARP: [1, 2],
  'VAR.P': [1, 2],
  MEDIAN: [1, 2],
  MODE: [1, 2],
  'MODE.SNGL': [1, 2],
  'MODE.MULT': [1, 2],
  CONCATENATE: [1, 2],
  CONCAT: [1, 2],
  TEXTJOIN: [2],
  NPV: [1, 2],
  TREND: [2, 3],
  GROWTH: [2, 3],
};

// Short variadic functions (fewer than 7 args but still take 1+ groups), so
// the syntax readout ends with an ellipsis: =IFS(test1, value1, [test2], …).
export const FUNCTION_VARIADIC: ReadonlySet<string> = new Set([
  'IFS',
  'SUMIFS',
  'COUNTIFS',
  'AVERAGEIFS',
  'MINIFS',
  'MAXIFS',
  'CHOOSE',
  'SWITCH',
]);

// Hand-written syntax for a few functions where the derivative arg list would
// read poorly (optional trailing args, variadic pairs, etc.).
export const FUNCTION_SYNTAX_OVERRIDES: Record<string, string> = {
  LET: '=LET(name1, value1, [name2, value2], …, calculation)',
  VLOOKUP: '=VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])',
  IF: '=IF(logical_test, value_if_true, [value_if_false])',
};