// Official Microsoft Excel function argument names.
// Sources: Microsoft Learn / Excel support documentation.

function generateSeries(prefix: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `${prefix}${i + 1}`);
}

export const FUNCTION_ARG_NAMES: Record<string, string[]> = {
  // Logical
  IF: ['logical_test', 'value_if_true', 'value_if_false'],
  IFERROR: ['value', 'value_if_error'],
  IFNA: ['value', 'value_if_na'],
  NOT: ['logical'],
  TRUE: [],
  FALSE: [],
  SWITCH: ['expression', 'value1', 'result1', 'default'],

  // Math / trig
  SUM: generateSeries('number', 30),
  AVERAGE: generateSeries('number', 30),
  AVERAGEA: generateSeries('value', 30),
  COUNT: generateSeries('value', 30),
  COUNTA: generateSeries('value', 30),
  COUNTIF: ['range', 'criteria'],
  MAX: generateSeries('number', 30),
  MIN: generateSeries('number', 30),
  PRODUCT: generateSeries('number', 30),
  ROUND: ['number', 'num_digits'],
  ROUNDUP: ['number', 'num_digits'],
  ROUNDDOWN: ['number', 'num_digits'],
  MROUND: ['number', 'multiple'],
  ABS: ['number'],
  SQRT: ['number'],
  POWER: ['number', 'power'],
  MOD: ['number', 'divisor'],
  INT: ['number'],
  FLOOR: ['number', 'significance'],
  'FLOOR.MATH': ['number', 'significance', 'mode'],
  CEILING: ['number', 'significance'],
  'CEILING.MATH': ['number', 'significance', 'mode'],
  SUMPRODUCT: generateSeries('array', 10),
  RAND: [],
  RANDBETWEEN: ['bottom', 'top'],
  PI: [],
  EXP: ['number'],
  LN: ['number'],
  LOG: ['number', 'base'],
  LOG10: ['number'],
  SIN: ['number'],
  COS: ['number'],
  TAN: ['number'],
  ASIN: ['number'],
  ACOS: ['number'],
  ATAN: ['number'],
  ATAN2: ['x_num', 'y_num'],
  SIGN: ['number'],
  TRUNC: ['number', 'num_digits'],

  // Lookup & reference
  VLOOKUP: ['lookup_value', 'table_array', 'col_index_num', 'range_lookup'],
  HLOOKUP: ['lookup_value', 'table_array', 'row_index_num', 'range_lookup'],
  XLOOKUP: ['lookup_value', 'lookup_array', 'return_array', 'if_not_found', 'match_mode', 'search_mode'],
  INDEX: ['array', 'row_num', 'column_num', 'area_num'],
  MATCH: ['lookup_value', 'lookup_array', 'match_type'],
  OFFSET: ['reference', 'rows', 'cols', 'height', 'width'],
  INDIRECT: ['ref_text', 'a1'],
  ROW: ['reference'],
  COLUMN: ['reference'],
  ROWS: ['array'],
  COLUMNS: ['array'],
  AREAS: ['reference'],

  // Text
  CONCATENATE: generateSeries('text', 30),
  CONCAT: generateSeries('text', 30),
  TEXTJOIN: ['delimiter', 'ignore_empty', ...generateSeries('text', 30)],
  LEFT: ['text', 'num_chars'],
  RIGHT: ['text', 'num_chars'],
  MID: ['text', 'start_num', 'num_chars'],
  LEN: ['text'],
  UPPER: ['text'],
  LOWER: ['text'],
  PROPER: ['text'],
  TRIM: ['text'],
  SUBSTITUTE: ['text', 'old_text', 'new_text', 'instance_num'],
  REPLACE: ['old_text', 'start_num', 'num_chars', 'new_text'],
  TEXT: ['value', 'format_text'],
  VALUE: ['text'],
  FIND: ['find_text', 'within_text', 'start_num'],
  SEARCH: ['find_text', 'within_text', 'start_num'],
  REPT: ['text', 'number_times'],
  CLEAN: ['text'],
  EXACT: ['text1', 'text2'],

  // Date & time
  TODAY: [],
  NOW: [],
  YEAR: ['serial_number'],
  MONTH: ['serial_number'],
  DAY: ['serial_number'],
  HOUR: ['serial_number'],
  MINUTE: ['serial_number'],
  SECOND: ['serial_number'],
  DATE: ['year', 'month', 'day'],
  TIME: ['hour', 'minute', 'second'],
  DATEDIF: ['start_date', 'end_date', 'unit'],
  WEEKDAY: ['serial_number', 'return_type'],
  WEEKNUM: ['serial_number', 'return_type'],
  EOMONTH: ['start_date', 'months'],
  EDATE: ['start_date', 'months'],
  WORKDAY: ['start_date', 'days', 'holidays'],
  NETWORKDAYS: ['start_date', 'end_date', 'holidays'],
  YEARFRAC: ['start_date', 'end_date', 'basis'],

  // Statistical
  STDEV: generateSeries('number', 30),
  'STDEV.S': generateSeries('number', 30),
  STDEVP: generateSeries('number', 30),
  'STDEV.P': generateSeries('number', 30),
  VAR: generateSeries('number', 30),
  'VAR.S': generateSeries('number', 30),
  VARP: generateSeries('number', 30),
  'VAR.P': generateSeries('number', 30),
  MEDIAN: generateSeries('number', 30),
  MODE: generateSeries('number', 30),
  'MODE.SNGL': generateSeries('number', 30),
  'MODE.MULT': generateSeries('number', 30),
  RANK: ['number', 'ref', 'order'],
  'RANK.EQ': ['number', 'ref', 'order'],
  'RANK.AVG': ['number', 'ref', 'order'],
  LARGE: ['array', 'k'],
  SMALL: ['array', 'k'],
  PERCENTILE: ['array', 'k'],
  'PERCENTILE.EXC': ['array', 'k'],
  'PERCENTILE.INC': ['array', 'k'],
  QUARTILE: ['array', 'quart'],
  'QUARTILE.EXC': ['array', 'quart'],
  'QUARTILE.INC': ['array', 'quart'],
  CORREL: ['array1', 'array2'],
  'COVARIANCE.P': ['array1', 'array2'],
  'COVARIANCE.S': ['array1', 'array2'],
  COVAR: ['array1', 'array2'],
  FORECAST: ['x', 'known_ys', 'known_xs'],
  'FORECAST.LINEAR': ['x', 'known_ys', 'known_xs'],
  TREND: ['known_ys', 'known_xs', 'new_xs', 'const'],
  GROWTH: ['known_ys', 'known_xs', 'new_xs', 'const'],
  'NORM.DIST': ['x', 'mean', 'standard_dev', 'cumulative'],
  NORMDIST: ['x', 'mean', 'standard_dev', 'cumulative'],
  'NORM.INV': ['probability', 'mean', 'standard_dev'],
  NORMINV: ['probability', 'mean', 'standard_dev'],

  // Information
  ISERROR: ['value'],
  ISNUMBER: ['value'],
  ISTEXT: ['value'],
  ISBLANK: ['value'],
  ISLOGICAL: ['value'],
  ISNA: ['value'],
  ISERR: ['value'],
  ISEVEN: ['number'],
  ISODD: ['number'],
  ISNONTEXT: ['value'],
  ISREF: ['value'],
  TYPE: ['value'],
  N: ['value'],
  NA: [],
  'ERROR.TYPE': ['error_val'],
  INFO: ['type_text'],
  CELL: ['info_type', 'reference'],

  // Financial
  PMT: ['rate', 'nper', 'pv', 'fv', 'type'],
  FV: ['rate', 'nper', 'pmt', 'pv', 'type'],
  PV: ['rate', 'nper', 'pmt', 'fv', 'type'],
  RATE: ['nper', 'pmt', 'pv', 'fv', 'type', 'guess'],
  NPER: ['rate', 'pmt', 'pv', 'fv', 'type'],
  NPV: ['rate', ...generateSeries('value', 30)],
  IRR: ['values', 'guess'],
  SLN: ['cost', 'salvage', 'life'],
  SYD: ['cost', 'salvage', 'life', 'per'],
  DB: ['cost', 'salvage', 'life', 'period', 'month'],
  DDB: ['cost', 'salvage', 'life', 'period', 'factor'],
  VDB: ['cost', 'salvage', 'life', 'start_period', 'end_period', 'factor', 'no_switch'],

  // Engineering
  DEC2BIN: ['number', 'places'],
  DEC2HEX: ['number', 'places'],
  DEC2OCT: ['number', 'places'],
  BIN2DEC: ['number'],
  BIN2HEX: ['number', 'places'],
  BIN2OCT: ['number', 'places'],
  HEX2DEC: ['number'],
  HEX2BIN: ['number', 'places'],
  HEX2OCT: ['number', 'places'],
  OCT2DEC: ['number'],
  OCT2BIN: ['number', 'places'],
  OCT2HEX: ['number', 'places'],
  BITAND: ['number1', 'number2'],
  BITOR: ['number1', 'number2'],
  BITXOR: ['number1', 'number2'],
  BITLSHIFT: ['number', 'shift_amount'],
  BITRSHIFT: ['number', 'shift_amount'],

  // Database
  DSUM: ['database', 'field', 'criteria'],
  DAVERAGE: ['database', 'field', 'criteria'],
  DCOUNT: ['database', 'field', 'criteria'],
  DMAX: ['database', 'field', 'criteria'],
  DMIN: ['database', 'field', 'criteria'],
  DGET: ['database', 'field', 'criteria'],
  DPRODUCT: ['database', 'field', 'criteria'],
  DSTDEV: ['database', 'field', 'criteria'],
  DSTDEVP: ['database', 'field', 'criteria'],
  DVAR: ['database', 'field', 'criteria'],
  DVARP: ['database', 'field', 'criteria'],

  // Array / dynamic
  TRANSPOSE: ['array'],
  UNIQUE: ['array', 'by_col', 'exactly_once'],
  SORT: ['array', 'sort_index', 'sort_order', 'by_col'],
  SORTBY: ['array', 'by_array1', 'sort_order1'],
  FILTER: ['array', 'include', 'if_empty'],
  SEQUENCE: ['rows', 'columns', 'start', 'step'],
  RANDARRAY: ['rows', 'columns', 'min', 'max', 'whole_number'],
};